In [1]:
from jax import grad, jit
from jax import random
import jax.numpy as np
from jax.ops import index, index_add, index_update

In [2]:
jax_array = np.zeros((3, 3))
print("original array:")
print(jax_array)

original array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
/Users/zhouji/anaconda3/envs/jax/lib/python3.8/site-packages/jax/lib/xla_bridge.py:119: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')


In [3]:
def f(array):
    return array[1,1]**5

In [4]:
new_jax_array = index_update(jax_array, index[1,:], 2.)
print(new_jax_array)

[[0. 0. 0.]
 [2. 2. 2.]
 [0. 0. 0.]]


In [5]:
grad(f)(new_jax_array)

DeviceArray([[ 0.,  0.,  0.],
             [ 0., 80.,  0.],
             [ 0.,  0.,  0.]], dtype=float32)

In [6]:
depth = -20
thickness = 20

corners=np.array([[-200,depth-thickness],
                  [-70,depth-thickness],
                  [70,depth-thickness],# bottom left coner
              [200,depth-thickness], 
              [200,depth], # bottom right coner
              [70, depth], # top right coner
              [-70,depth],# top left coner
              [-200,depth]])
Number_para = 3
obs_N = 8
points = np.empty((2*Number_para+8,2),dtype = np.float32)

In [7]:
points = index_update(points,index[0],corners[0])
points = index_update(points,index[1],corners[1])

for i in range(6):
    points = index_update(points, index[Number_para+i],corners[i])
points=index_update(points,index[-2],corners[-2])
points=index_update(points,index[-1],corners[-1])

In [8]:
points

DeviceArray([[-200.,  -40.],
             [ -70.,  -40.],
             [   0.,    0.],
             [-200.,  -40.],
             [ -70.,  -40.],
             [  70.,  -40.],
             [ 200.,  -40.],
             [ 200.,  -20.],
             [  70.,  -20.],
             [   0.,    0.],
             [   0.,    0.],
             [   0.,    0.],
             [ -70.,  -20.],
             [-200.,  -20.]], dtype=float32)

In [97]:
jax.random.seed(1)

NameError: name 'jax' is not defined